I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 81, in script
    if part1found:
  File "game/script.rpy", line 81, in <module>
    if part1found:
NameError: name 'part1found' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 81, in script
    if part1found:
  File "/Volumes/renpy-8.2.3-sdk/renpy-8.2.3-sdk/renpy/ast.py", line 1845, in execute
    if renpy.python.py_eval(condition):
  File "/Volumes/renpy-8.2.3-sdk/renpy-8.2.3-sdk/renpy/python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Volumes/renpy-8.2.3-sdk/renpy-8.2.3-sdk/renpy/python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 81, in <module>
    if part1found:
NameError: name 'part1found' is not defined

macOS-15.0.1-arm64-arm-64bit arm64
Ren'Py 8.2.3.24061702
Final Build 1.0
Sun Nov 10 10:36:09 2024
